### ISSUE TITLE
DuckDuckGo support

### ISSUE THREAD

**Issue by wey-gu** [Endle/fireSeqSearch#17]
As titled.
Great work, thanks!

**Comment by Endle** [comment]
Hi @wey-gu , I'm adding Duckduckgo support

![Screenshot 2022-05-17 at 16-33-29 softmax at DuckDuckGo](https://user-images.githubusercontent.com/3221521/168905198-b126cbd0-64e7-46fb-a6b2-689144ecc8ac.png)

Without thinking about the DOM structure of duckduckgo too much, the render is just usable

**Comment by Endle** [comment]
Done in https://github.com/Endle/fireSeqSearch/releases/tag/0.0.6

I'll close this issue when Mozilla approves my update

**Comment by Endle** [comment]
0.0.6 is available now

https://addons.mozilla.org/en-CA/firefox/addon/fireseqsearch/versions/

**Comment by wey-gu** [comment]
Amazing @Endle ! Thanks!!!
