### ISSUE TITLE
Failed to open link. Cannot match graph identifier `logseq_notebook` to any linked graph.

### ISSUE THREAD

**Issue by Explorare** [Endle/fireSeqSearch#20]
[Issue]
Logseq failed to open the URI with an error message:
>Failed to open link. Cannot match graph identifier `logseq_notebook` to any linked graph.

Search results are correct. 

[Env]
fire_seq_search_server v0.0.5
fireSeqSearch for Firefox v0.0.6
Logseq v0.6.9
Windows 10 21H1

**Comment by Endle** [comment]
Hi @Explorare , thank you for reporting this issue. May I ask for a few more questions about it?

1. How did you launch fire_seq_search_server? PowerShell? What's the command you were using?
2. I assume you can see the correct titles on the web page. Is my guess correct?

There is a parameter `--notebook_name`, I added it, but not documented it yet. https://github.com/Endle/fireSeqSearch/blob/79af3837cab46decdef1fe8bb34145dcb2f9bd77/fire_seq_search_server/src/main.rs#L36

Could you please try 
```
.\fire_seq_search_server.exe --notebook_path C:\Users\li\logseq_notebook --notebook_name LogseqNotebookName
```

**Comment by Explorare** [comment]
I tried to run the server through cmd and PowerShell 7, and got the same result.
```
$ .\fire_seq_search_server.exe --notebook_path C:\Users\explo\Documents\Logseq --notebook_name Logseq
[INFO ] save metas
[INFO ] Preparing commit
[INFO ] Starting merge  - [Seg("274d9eca"), Seg("10596cb9"), Seg("0e5df311"), Seg("41750180"), Seg("9e666f97"), Seg("619b8dc7"), Seg("e4e13444"), Seg("32388e75")]
[INFO ] Prepared commit 284
[INFO ] committing 284
[INFO ] save metas
[INFO ] Running garbage collection
[INFO ] Garbage collect
[INFO ] Server::run; addr=127.0.0.1:3030
[INFO ] listening on http://127.0.0.1:3030
[INFO ] Searching nlp transformer
[INFO ] Found doc addr DocAddress { segment_ord: 0, doc_id: 39 }, score 15.701874
[INFO ] Found doc addr DocAddress { segment_ord: 5, doc_id: 20 }, score 10.664612
[INFO ] Found doc addr DocAddress { segment_ord: 3, doc_id: 24 }, score 10.265078
[INFO ] Found doc addr DocAddress { segment_ord: 2, doc_id: 0 }, score 10.25067
[INFO ] Found doc addr DocAddress { segment_ord: 5, doc_id: 27 }, score 8.030888
[INFO ] Found doc addr DocAddress { segment_ord: 1, doc_id: 5 }, score 5.200621
[INFO ] Found doc addr DocAddress { segment_ord: 4, doc_id: 5 }, score 2.7373874
[INFO ] Found doc addr DocAddress { segment_ord: 5, doc_id: 11 }, score 1.9310763
[INFO ] Found doc addr DocAddress { segment_ord: 7, doc_id: 11 }, score 1.0827819
[INFO ] Search result ["{\"title\":[\"Transformer Neural Network\"]}","{\"title\":[\"Natural Language Processing\"]}","{\"title\":[\"Research Proposal\"]}","{\"title\":[\"@exploring transformer-based contextual knowledge graph embeddings_ how the design of the attention mask and the input structure affect learning in transformer models\"]}","{\"title\":[\"Response\"]}","{\"title\":[\"Color\"]}","{\"title\":[\"clips.What is a Knowledge Graph_\"]}","{\"title\":[\"hls__Holmström_2021_Exploring Transformer-Based Contextual Knowledge Graph Embeddings\"]}","{\"title\":[\"Knowledge Graph\"]}"]
```
Click the link in browser won't bring the windows of Logseq to front. And the error message showed up.

I've tried to re-index the graph but didn't help. Tried to create a new repo but didn't help.

There is a new line append to log of Logseq every time I click the link
```
[2022-05-21 08:21:56.076] [info] open-url {:url "logseq://graph/logseq_notebook?page=Transformer%20Neural%20Network"}
```

And the URI for a page that Logseq provided is 
```
[2022-05-21 08:33:04.305] [info] open-url {:url "logseq://graph/Logseq?page=Research%20Proposal"}
```

So I guess the variable `logseq_notebook` didn't get the right value?

**Comment by Endle** [comment]
My bad! Sorry for my foolish bug.

The fix is in v0.0.8. Just wait Mozilla to approve my update https://addons.mozilla.org/en-US/developers/addon/fireseqsearch/edit

**Comment by Explorare** [comment]
Commit 62b70ef didn't fix the issue correctly. The value of `notebook_name` is set to `notebook_path` by mistake. 
```
[2022-05-21 11:51:58.521] [info] open-url {:url "logseq://graph/C:%5CUsers%5Cexplo%5CDocuments%5CLogseq?page=Natural%20Language%20Processing"}
```

**Comment by Explorare** [comment]
I forgot to append the `--notebook_name` option. With the correct value of `notebook_name` been set, it works as intended. Thanks for the hotfix.
