### ISSUE TITLE
Move results to the right side panel.

### ISSUE THREAD

**Issue by Explorare** [Endle/fireSeqSearch#21]
It would be better to put the query result to the right side, in a panel, just like the Google does. Like this
![image](https://user-images.githubusercontent.com/5090766/169653552-b69da4fb-fa82-47e1-9309-4aaa273799e2.png)

**Comment by Endle** [comment]
Hi @Explorare 

Thank you so much for your suggestion! I'm unsatisfied with the current UIUX and I'm thinking of how to improve it.

My current js implement is too hacky, and I'm thinking of refactoring it. After that, I will be able to adopt a better UI

**Comment by Endle** [comment]
@Explorare Sorry for my late update. After some refactor work, I'm planning to add an experimental layout (facilitate the right side of Google). 

However, the DOM tree of google.com is quite confusing to me, and I have no idea of how to insert a DOM element into that area now.

Do you know if there is any open-source browser extension or GreaseMonkey Script which is utilizing that area?

Thank you

**Comment by Explorare** [comment]
I didn't find a script to modify the right side panel, but found this
[搜索引擎切换器 / Search Engine Switcher](https://greasyfork.org/en/scripts/446492-%E6%90%9C%E7%B4%A2%E5%BC%95%E6%93%8E%E5%88%87%E6%8D%A2%E5%99%A8-search-engine-switcher)

It adds a left panel.

Thanks for your effort on this plugin.

**Comment by Endle** [comment]
> I didn't find a script to modify the right side panel, but found this [搜索引擎切换器 / Search Engine Switcher](https://greasyfork.org/en/scripts/446492-%E6%90%9C%E7%B4%A2%E5%BC%95%E6%93%8E%E5%88%87%E6%8D%A2%E5%99%A8-search-engine-switcher)
> 
> It adds a left panel.
> 
> Thanks for your effort on this plugin.

Thank you. I'll have a look

**Comment by Endle** [comment]
I added an experimental layout
![image](https://user-images.githubusercontent.com/3221521/187054310-8763ad21-d84a-4b25-a0d7-a73d392129ac.png)

One can check the Experimental Layout in extension setting

**Comment by Endle** [comment]
0.0.13 version has been approved by Mozilla  https://addons.mozilla.org/en-CA/firefox/addon/fireseqsearch/versions/

![image](https://user-images.githubusercontent.com/3221521/187054532-70579b06-11ea-4c2c-ad09-62d7be40ef01.png)


In extension setting, check `Experimental Layout`, then refresh the page, the fireSeqSearch box should appear at right


I'll close this issue now, although I'll definitely keep working on the layout. I'm not satisfied with its aesthetics.
