### ISSUE TITLE
不支持iCloud路径？

### ISSUE THREAD

**Issue by willzhqiang** [Endle/fireSeqSearch#23]
刚才试了一下，我用的是iCloud同步。
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/279170/170860579-0120a1ec-f1f7-4d28-b050-048f3aa5d2d7.png">

**Comment by Endle** [comment]
请问你输入的命令是什么呢？看到第一行，我猜测是漏掉了 `--notebook_path`



运行
```
/path/to/fire_seq_search_server --notebook_path "/Users/..../Work"
```
的结果是什么呢？

**Comment by willzhqiang** [comment]
Projects/fireSeqSearch/fire_seq_search_server/target/debug/fire_seq_search_server --notebook_path "/Users/Qiang/Library/Mobile Documents/iCloud~com~logseq~logseq/Documents/Work"
[INFO ] fire_seq_search guess the notebook name is Work
[INFO ] save metas
thread 'main' panicked at 'Something went wrong reading the file: Error { kind: InvalidData, message: "stream did not contain valid UTF-8" }', src/main.rs:150:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
不知道这个是什么错误，我的是
macOS Monterey
Version 12.4
Word一个一个Graph的文件夹,里面有pages logseq asserts journals 等文件夹。

**Comment by Endle** [comment]
你好，这的确是一个 bug，我看了一遍代码，一时找不到原因所在。请问能提供更详细一些的log吗？步骤如下

1. git pull 并 cargo build
2. `RUST_BACKTRACE=1 RUST_LOG=debug /path/to/fire_seq_search_server  --notebook_path "/Users/..../Work"`

debug log 里可能有一些sensitive的信息，发送之前可能要剪裁。如果有需要的话，可以把log发到我的邮箱里 lizhenbo at yahoo com

谢谢你的协助

**Comment by Endle** [comment]
> 我看日志应该是没有处理好Mac下面常见的.DS_Store

谢谢反馈，的确是这里的问题。刚才发了一个过滤掉文件夹的选项。

不过我查了一下，.DS_Store是文件夹而非文件夹 ，我刚才的修正解决不了问题。我再改一下我的代码

**Comment by Endle** [comment]
我在这个 commit 里修复了，方便测试一下吗？ https://github.com/Endle/fireSeqSearch/commit/e898e97f8f0ef533afe81c8cdd885e8351b6350c

**Comment by willzhqiang** [comment]
> 我在这个 commit 里修复了，方便测试一下吗？ https://github.com/Endle/fireSeqSearch/commit/e898e97f8f0ef533afe81c8cdd885e8351b6350c

收到，近期有时间了会测试下

**Comment by Endle** [comment]
@willzhqiang 请问这个问题在最新版本的 fire_seq_search_server 里还有吗？
