### ISSUE TITLE
Need a better logo

### ISSUE THREAD

**Issue by Endle** [Endle/fireSeqSearch#33]

**Comment by yoyurec** [comment]
what about this one?
![image](https://user-images.githubusercontent.com/137919/200795268-da447a8d-f4e2-46ac-b50b-8e6800e8b837.png)
"notes + browser search"
https://www.flaticon.com/free-icon/web-browser_7328762

**Comment by yoyurec** [comment]
BTW, if the plugin is now not only for Firefox - is the name **fire**SeqSearch is actual anymore? )
maybe rename to something like LogseqSearchAssistant or smth...

**Comment by Endle** [comment]
Thank you so much! The icon 
https://www.flaticon.com/free-icon/web-browser_7328762 is amazing.


I tend to keep the current name. Although fireSeqSearch is not Firefox-only now, it could be interpreted as "ignite your mind" or something... Well, I'm just too sticked to the old name :)
