### ISSUE TITLE
violentmonkey version in chrome, search result not show in the page, but http://127.0.0.1:3030/query/keywords works

### ISSUE THREAD

**Issue by saccohuo** [Endle/fireSeqSearch#51]
violentmonkey version in chrome, search result not show in the page, but http://127.0.0.1:3030/query/keywords works

**Comment by saccohuo** [comment]
Can you leave your email address, so I can send the output to you.

**Comment by Endle** [comment]
> Can you leave your email address, so I can send the output to you.

lizhenbo (at) yahoo (dot) com

I promise that (1) I would not release them to third party and (ii) I'll delete them after troubleshooting

**Comment by Endle** [comment]
I'm sorry that I have not received your log yet. Maybe mail server blocked the logs?

If you like, you could try to send these logs to me by Discord / Matrix(Element.io) / Telegram

**Comment by saccohuo** [comment]
> 

Sent to you mailbox just now.

**Comment by Endle** [comment]
Hi @saccohuo 

Thank you for your log. Can you try this file?

https://github.com/Endle/fireSeqSearch/raw/02821d6cdaa8c09cf6e4cdcb7eae0ad1cddc01b2/fireSeqSearch_addon/violentmonkeyscript.user.js

**Comment by saccohuo** [comment]
It just works after the first time I reinstall the script.
The 2rd serach fail either. I have to reinstall the script to make it take effect.

**Comment by saccohuo** [comment]
After a moment and reinstall some times, it works correctly, thanks.

**Comment by saccohuo** [comment]
> After a moment and reinstall some times, it works correctly, maybe it was indexing.
Thanks.

**Comment by saccohuo** [comment]
It is not stable, sometimes works, sometimes fail.

**Comment by Endle** [comment]
The reason that Violent monkey doesn't work is Violentmonkey using a different syntax to grant permissions.
See https://github.com/Endle/fireSeqSearch/pull/76/files#diff-ab382aa8ff96a21b787abc4159aa094c3455f67ba66e5dd55adaf4b7e7a341ebR10

As you mentioned that 
> sometimes works, sometimes fail.
My first guess is you triggered another issue in fireSeqSearch, which is not only for violent monkey.

Please feel free to open another issue to report these bugs.

Thank you.
