### ISSUE TITLE
Bad display when block is long

### ISSUE THREAD

**Issue by Endle** [Endle/fireSeqSearch#57]
https://github.com/Endle/fireSeqSearch/releases/tag/0.0.16

Deficient

If the block is very long, for example, you clipped a long article into logseq, then the summary would be hard (or useless) to read. That's why there is a "Hide Summary" button.

**Comment by todrobbins** [comment]
What about trying a `flexbox` multi-column layout? I could give the design a go

**Comment by Endle** [comment]
> What about trying a `flexbox` multi-column layout?

Thank you for your suggestion. Currently, I consider it as a server side issue, as a long paragraph will be entirely included in the summary
