### ISSUE TITLE
Feature Request: read/search PDF contents as well

### ISSUE THREAD

**Issue by cliffordx** [Endle/fireSeqSearch#63]
I suggest a feature to read/search PDF contents as well? or is this too much to ask for as a feature. Thanks!

**Comment by Endle** [comment]
Sounds interesting. 
How about: if a page has a link to a pdf file, then try to add all the information into this page?

I'll have a look on it, and check how hard it is.

**Comment by cliffordx** [comment]
> How about: if a page has a link to a pdf file, then try to add all the information into this page?

May be doable. Extract the search "query" and put/dump it into the page linked to the PDF.

**Comment by Endle** [comment]
I'm working on this idea now: https://github.com/Endle/fireSeqSearch/pull/114

The current dev branch should work now, would you like to have a try?

Some flaws
1. When enabling PDF query, the performance would drop. I'll evaluate if the impact is severe.
2. The dependency, pdf-extract, I'm not using it's main branch, so `cargo package` is failing, blocking me from making the next fireSeqSearch release

**Comment by Endle** [comment]
This feature has been done in https://github.com/Endle/fireSeqSearch/releases/tag/0.1.2
