### ISSUE TITLE
Journals are not considered in the search

### ISSUE THREAD

**Issue by Endle** [Endle/fireSeqSearch#65]
If anyone wants to search in journals, please let me know, and I'll consider to implement it

**Comment by cliffordx** [comment]
I also like to search my journals too. That would be awesome, aside from the pdf FR I just requested.

**Comment by Endle** [comment]
Closed now. 

There's still improvement to be done

> Currently, I haven't figured out an approach to generate the Logseq URI for a specific journal page.

I'll leave it as another issue
