### ISSUE TITLE
Chrome violent monkey version, click the item in google results, not go to the item in logseq, just go to logseq journal page

### ISSUE THREAD

**Issue by saccohuo** [Endle/fireSeqSearch#81]
click the item in results, not go to the item in logseq, just go to logseq journal page

version: https://github.com/Endle/fireSeqSearch/raw/02821d6cdaa8c09cf6e4cdcb7eae0ad1cddc01b2/fireSeqSearch_addon/violentmonkeyscript.user.js

**Comment by Endle** [comment]
Can you send the href of the generated result? Thanks

**Comment by saccohuo** [comment]
logseq://graph/D:\Dropbox\logseq\roam?page=%E9%81%BF%E9%9B%B7%E9%92%88%20-%20%E7%BB%B4%E5%9F%BA%E7%99%BE%E7%A7%91%EF%BC%8C%E8%87%AA%E7%94%B1%E7%9A%84%E7%99%BE%E7%A7%91%E5%85%A8%E4%B9%A6%20(highlights)

**Comment by Endle** [comment]
This is a bit weird. Can you try to run fireSeqSearch with both

1. use latest release https://github.com/Endle/fireSeqSearch/releases/tag/0.0.23
2. Specify both `--notebook_path` and `--notebook_name`

Thanks

**Comment by saccohuo** [comment]
How can I specify notebook_name, I cannot find it in README.

**Comment by Endle** [comment]
> How can I specify notebook_name, I cannot find it in README.

Sorry, I haven't updated the README yet


You can always use `fire_seq_search_server -h` to check the parameters

In this case, you can try
`fire_seq_search_server --notebook_path /home/li/path --notebook_name name`

**Comment by saccohuo** [comment]
Thanks, it works, example like:  `fire_seq_search_server.exe --notebook_path D:\logseq\roam --notebook_name roam`
