### ISSUE TITLE
Logseq 0.8.15 now supports local http server API.

### ISSUE THREAD

**Issue by byheaven** [Endle/fireSeqSearch#96]
Is it possible to use the original service? Thank you!

**Comment by Endle** [comment]
That's an appealing idea. If the server side of fireSeqSearch could be implemented as a logseq plugin, then there could be lots of benefits.

1. Easier for me to push updates
2. Don't need to run another app at startup
3. Reuse some logseq libs


However, my current implementation is **strongly** coupled with Rust and tantivy. Moving to local HTTP server means that I need to rewrite the program totally, and I don't know if this is possible.

I'm open to discussing this idea, but I don't think I'll work on it in the foreseeable future.

Thank you again for your suggestion

**Comment by xxchan** [comment]
Currently Logseq only has datalog query API, instead of the page & fulltext search API, so I think this won't be trivial. But I submitted a feature request to Logseq :) https://discuss.logseq.com/t/add-support-for-page-fulltext-search-api/13842

**Comment by byheaven** [comment]
As far as I know (from the WeChat group), they are developing the full text searching tools now.

**Comment by Endle** [comment]
I'm going to support Obsidian as Tier 1 target, so I'll avoid logseq-only APIs when possible.
